//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.01 at 04:40:36 PM WEST 
//


package ensa.pay.cmiclientexchanger.soap.api.creancier;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for creancierInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="creancierInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="nameCreancier" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="codeCreancier" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="categoryCreancier" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="listCreances" type="{http://app.com/creanciers-service}creanceInfo" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "creancierInfo", propOrder = {
    "id",
    "nameCreancier",
    "codeCreancier",
    "categoryCreancier",
    "listCreances"
})
public class CreancierInfo {

    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected String nameCreancier;
    @XmlElement(required = true)
    protected String codeCreancier;
    @XmlElement(required = true)
    protected String categoryCreancier;
    @XmlElement(nillable = true)
    protected List<CreanceInfo> listCreances;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the nameCreancier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameCreancier() {
        return nameCreancier;
    }

    /**
     * Sets the value of the nameCreancier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameCreancier(String value) {
        this.nameCreancier = value;
    }

    /**
     * Gets the value of the codeCreancier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeCreancier() {
        return codeCreancier;
    }

    /**
     * Sets the value of the codeCreancier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeCreancier(String value) {
        this.codeCreancier = value;
    }

    /**
     * Gets the value of the categoryCreancier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryCreancier() {
        return categoryCreancier;
    }

    /**
     * Sets the value of the categoryCreancier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryCreancier(String value) {
        this.categoryCreancier = value;
    }

    /**
     * Gets the value of the listCreances property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the listCreances property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getListCreances().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreanceInfo }
     * 
     * 
     */
    public List<CreanceInfo> getListCreances() {
        if (listCreances == null) {
            listCreances = new ArrayList<CreanceInfo>();
        }
        return this.listCreances;
    }

}
