//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.01 at 04:40:36 PM WEST 
//


package ensa.pay.cmiclientexchanger.soap.api.creancier;

import lombok.Data;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="listCreanciers" type="{http://app.com/creanciers-service}creancierInfo" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "listCreanciers"
})
@Data
@XmlRootElement(name = "getListCreanciersResponse")
public class GetListCreanciersResponse {

    @XmlElement(nillable = true)
    protected List<CreancierInfo> listCreanciers;

    /**
     * Gets the value of the listCreanciers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the listCreanciers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getListCreanciers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreancierInfo }
     * 
     * 
     */
    public List<CreancierInfo> getListCreanciers() {
        if (listCreanciers == null) {
            listCreanciers = new ArrayList<CreancierInfo>();
        }
        return this.listCreanciers;
    }

}
