//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.01 at 04:40:36 PM WEST 
//


package ensa.pay.cmiclientexchanger.soap.api.creancier;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ensa.pay.cmiclientexchanger.soap.api.creancier package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ensa.pay.cmiclientexchanger.soap.api.creancier
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetListCreanciersRequest }
     * 
     */
    public GetListCreanciersRequest createGetListCreanciersRequest() {
        return new GetListCreanciersRequest();
    }

    /**
     * Create an instance of {@link GetListCreanciersResponse }
     * 
     */
    public GetListCreanciersResponse createGetListCreanciersResponse() {
        return new GetListCreanciersResponse();
    }

    /**
     * Create an instance of {@link CreancierInfo }
     * 
     */
    public CreancierInfo createCreancierInfo() {
        return new CreancierInfo();
    }

    /**
     * Create an instance of {@link CreanceInfo }
     * 
     */
    public CreanceInfo createCreanceInfo() {
        return new CreanceInfo();
    }

}
