//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.03 at 01:35:06 PM WEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://app.com/payments-service", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ensa.pay.cmiclientexchanger.soap.api.creancier;
