//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.03 at 01:35:06 PM WEST 
//


package ensa.pay.cmiclientexchanger.soap.api.creancier;

import lombok.AllArgsConstructor;
import lombok.Data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="billID" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="accountID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="creancier" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "billID",
    "accountID",
    "creancier"
})
@XmlRootElement(name = "paymentRequest")

public class PaymentRequest {

    protected long billID;
    @XmlElement(required = true)
    protected String accountID;
    @XmlElement(required = true)
    protected String creancier;

    /**
     * Gets the value of the billID property.
     * 
     */
    public long getBillID() {
        return billID;
    }

    /**
     * Sets the value of the billID property.
     * 
     */
    public void setBillID(long value) {
        this.billID = value;
    }

    /**
     * Gets the value of the accountID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountID() {
        return accountID;
    }

    /**
     * Sets the value of the accountID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountID(String value) {
        this.accountID = value;
    }

    /**
     * Gets the value of the creancier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreancier() {
        return creancier;
    }

    /**
     * Sets the value of the creancier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreancier(String value) {
        this.creancier = value;
    }

}
